title: Properties
modelClass: Shohabbos\Matcher\Models\Property
list: $/shohabbos/matcher/models/property/columns.yaml
recordUrl: 'shohabbos/matcher/properties/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
showTree: 1
treeExpanded: 1
