name: Properties
modelClass: Shohabbos\Matcher\Models\Property
form: $/shohabbos/matcher/models/property/fields.yaml
defaultRedirect: shohabbos/matcher/properties
create:
    redirect: 'shohabbos/matcher/properties/update/:id'
    redirectClose: shohabbos/matcher/properties
update:
    redirect: shohabbos/matcher/properties
    redirectClose: shohabbos/matcher/properties
preview: {  }
