plugin:
    name: 'shohabbos.matcher::lang.plugin.name'
    description: 'shohabbos.matcher::lang.plugin.description'
    author: Shohabbos
    icon: oc-icon-whatsapp
    homepage: ''
permissions:
    manage_profiles:
        tab: 'shohabbos.matcher::lang.plugin.name'
        label: 'Manage profiles'
navigation:
    matcher-profiles:
        label: Matcher
        url: shohabbos/matcher/profiles
        icon: icon-life-ring
        sideMenu:
            matcher-profiles:
                label: Profiles
                url: shohabbos/matcher/profiles
                icon: icon-sitemap
