plugin:
    name: 'shohabbos.matcher::lang.plugin.name'
    description: 'shohabbos.matcher::lang.plugin.description'
    author: Shohabbos
    icon: oc-icon-whatsapp
    homepage: ''
permissions:
    manage_profiles:
        tab: 'shohabbos.matcher::lang.plugin.name'
        label: 'Manage profiles'
    manage_properties:
        tab: 'shohabbos.matcher::lang.plugin.name'
        label: 'Manage properties'
navigation:
    matcher-profiles:
        label: Profiles
        url: shohabbos/matcher/profiles
        icon: icon-users
        sideMenu:
            matcher-profiles:
                label: Profiles
                url: shohabbos/matcher/profiles
                icon: icon-users
            matcher-properties:
                label: Properties
                url: shohabbos/matcher/properties
                icon: icon-table
